In [1]:
import pandas as pd

In [2]:
f=pd.read_csv('fifa_eda.csv')

In [5]:
f[:2]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0

In [6]:
f.head(2)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0

In [8]:
f.isna().sum().sort_values(ascending=False)

Contract Valid Until        289
Value                       252
Club                        241
International Reputation     48
Skill Moves                  48
ID                            0
Name                          0
Potential                     0
Age                           0
Nationality                   0
Preferred Foot                0
Wage                          0
Overall                       0
Position                      0
Joined                        0
Height                        0
Weight                        0
Release Clause                0
dtype: int64

In [12]:
f.isnull().sum().sort_values(ascending=False)

Contract Valid Until        289
Value                       252
Club                        241
International Reputation     48
Skill Moves                  48
ID                            0
Name                          0
Potential                     0
Age                           0
Nationality                   0
Preferred Foot                0
Wage                          0
Overall                       0
Position                      0
Joined                        0
Height                        0
Weight                        0
Release Clause                0
dtype: int64

In [15]:
f['Club'].shape

(18207,)

In [17]:
f['Club'].value_counts()

Club
RC Celta               33
Everton                33
Valencia CF            33
Borussia Dortmund      33
TSG 1899 Hoffenheim    33
                       ..
Botafogo               20
Vitória                20
Sligo Rovers           19
Limerick FC            19
Derry City             18
Name: count, Length: 651, dtype: int64

In [30]:
f['Club'].fillna('Unknown class',inplace=True)

In [31]:
f['Club'].sort_values(ascending=False)

8798            Śląsk Wrocław
10524           Śląsk Wrocław
17567           Śląsk Wrocław
7910            Śląsk Wrocław
7228            Śląsk Wrocław
                 ...
8337      SSV Jahn Regensburg
11861     SSV Jahn Regensburg
11244     SSV Jahn Regensburg
4587      SSV Jahn Regensburg
6184      SSV Jahn Regensburg
Name: Club, Length: 18207, dtype: object

In [32]:
f.isna().sum()

ID                            0
Name                          0
Age                           0
Nationality                   0
Overall                       0
Potential                     0
Club                          0
Value                       252
Wage                          0
Preferred Foot                0
International Reputation     48
Skill Moves                  48
Position                      0
Joined                        0
Contract Valid Until        289
Height                        0
Weight                        0
Release Clause                0
dtype: int64

In [22]:
f.dropna()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [33]:
f

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [38]:
v_avg=f['Value'].mean().round(2)
print(v_avg)

2444.53

In [39]:
f['Preferred Foot']

0         Left
1        Right
2        Right
3        Right
4        Right
         ...
18202    Right
18203    Right
18204    Right
18205    Right
18206    Right
Name: Preferred Foot, Length: 18207, dtype: object

In [40]:
f['Preferred Foot'].map({'Left':0,'Right':1})

0        0
1        1
2        1
3        1
4        1
        ..
18202    1
18203    1
18204    1
18205    1
18206    1
Name: Preferred Foot, Length: 18207, dtype: int64

In [46]:
f['Preferred Foot']=f['Preferred Foot'].apply(lambda x: 0 if x=='Left' else 1)

In [49]:
f[f['Preferred Foot']==1]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,1,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,1,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,1,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,1,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
5,183277,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,1,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,1,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,1,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,1,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,1,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,1,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [51]:
f.groupby('Preferred Foot').get_group(1)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,1,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,1,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,1,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,1,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
5,183277,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,1,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,1,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,1,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,1,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,1,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,1,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [52]:
f.groupby('Preferred Foot').get_group(0)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,0,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
13,168542,David Silva,32,Spain,90,90,Manchester City,60000.0,285.0,0,4.0,4.0,LCM,2010,2020-01-01,5.666667,148.0,111000.0
15,211110,P. Dybala,24,Argentina,89,94,Juventus,89000.0,205.0,0,3.0,4.0,LF,2015,2022-01-01,5.833333,165.0,153500.0
17,194765,A. Griezmann,27,France,89,90,Atlético Madrid,78000.0,145.0,0,4.0,4.0,CAM,2014,2023-01-01,5.750000,161.0,165800.0
19,192119,T. Courtois,26,Belgium,89,90,Real Madrid,53500.0,240.0,0,4.0,1.0,GK,2018,2024-01-01,6.500000,212.0,113700.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18172,243636,C. Hawkins,18,England,48,65,Burton Albion,50.0,1.0,0,1.0,1.0,GK,2018,2019-01-01,6.166667,165.0,119.0
18175,243649,E. Clarke,19,England,48,59,Fleetwood Town,40.0,1.0,0,1.0,2.0,LB,2018,2019-01-01,5.666667,154.0,78.0
18191,245570,J. Norville-Williams,18,England,47,65,Cambridge United,50.0,1.0,0,1.0,2.0,LB,2018,2021-01-01,5.916667,168.0,119.0
18200,231381,J. Young,18,Scotland,47,62,Swindon Town,60.0,1.0,0,1.0,2.0,ST,2015,2019-01-01,5.750000,157.0,143.0
18201,243413,D. Walsh,18,Republic of Ireland,47,68,Waterford FC,60.0,1.0,0,1.0,2.0,RB,2018,2018-01-01,6.083333,168.0,153.0

In [57]:
f.groupby('Nationality').get_group('Brazil')

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,1,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.000000
27,200145,Casemiro,26,Brazil,88,90,Real Madrid,59500.0,285.0,1,3.0,2.0,CDM,2013,2021-01-01,6.083333,185.0,126400.000000
32,189242,Coutinho,26,Brazil,88,89,FC Barcelona,69500.0,340.0,1,3.0,5.0,LW,2018,2023-01-01,5.666667,150.0,147700.000000
35,176676,Marcelo,30,Brazil,88,88,Real Madrid,43000.0,285.0,0,4.0,5.0,LB,2007,2022-01-01,5.750000,176.0,88200.000000
39,164240,Thiago Silva,33,Brazil,88,88,Paris Saint-Germain,24000.0,165.0,1,4.0,2.0,RCB,2012,2020-01-01,6.000000,181.0,44400.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17059,243750,Gianluca Zanette,21,Brazil,55,66,Vejle Boldklub,120.0,1.0,1,1.0,1.0,GK,2018,2020-01-01,6.166667,176.0,174.000000
17446,235949,Strefezza,21,Brazil,54,62,US Cremonese,100.0,2.0,1,1.0,2.0,RW,2016,2019-06-30,5.500000,148.0,4585.060806
17588,244311,Lucas Ribeiro,19,Brazil,53,71,Valenciennes FC,130.0,1.0,0,1.0,2.0,LM,2018,2019-01-01,5.666667,132.0,309.000000
17611,241268,Felipe Ferreyra,20,Brazil,53,67,Curicó Unido,130.0,1.0,1,1.0,2.0,ST,2016,2022-01-01,5.750000,159.0,257.000000
18170,246447,Nicolas Firmino,17,Brazil,48,70,New England Revolution,60.0,1.0,1,1.0,2.0,CAM,2018,2021-01-01,5.916667,154.0,147.000000

In [56]:
f['Nationality'].unique()

array(['Argentina', 'Portugal', 'Brazil', 'Spain', 'Belgium', 'Croatia',
       'Uruguay', 'Slovenia', 'Poland', 'Germany', 'France', 'England',
       'Italy', 'Egypt', 'Colombia', 'Denmark', 'Gabon', 'Wales',
       'Senegal', 'Costa Rica', 'Slovakia', 'Netherlands',
       'Bosnia Herzegovina', 'Morocco', 'Serbia', 'Algeria', 'Austria',
       'Greece', 'Chile', 'Sweden', 'Korea Republic', 'Finland', 'Guinea',
       'Montenegro', 'Armenia', 'Switzerland', 'Norway', 'Czech Republic',
       'Scotland', 'Ghana', 'Central African Rep.', 'DR Congo',
       'Ivory Coast', 'Russia', 'Ukraine', 'Iceland', 'Mexico', 'Jamaica',
       'Albania', 'Venezuela', 'Japan', 'Turkey', 'Ecuador', 'Paraguay',
       'Mali', 'Nigeria', 'Cameroon', 'Dominican Republic', 'Israel',
       'Kenya', 'Hungary', 'Republic of Ireland', 'Romania',
       'United States', 'Cape Verde', 'Australia', 'Peru', 'Togo',
       'Syria', 'Zimbabwe', 'Angola', 'Burkina Faso', 'Iran', 'Estonia',
       'Tunisia', 'Equatorial Guinea', 'New Zealand', 'FYR Macedonia',
       'United Arab Emirates', 'China PR', 'Guinea Bissau', 'Bulgaria',
       'Kosovo', 'South Africa', 'Madagascar', 'Georgia', 'Tanzania',
       'Gambia', 'Cuba', 'Belarus', 'Uzbekistan', 'Benin', 'Congo',
       'Mozambique', 'Honduras', 'Canada', 'Northern Ireland', 'Cyprus',
       'Saudi Arabia', 'Curacao', 'Moldova', 'Bolivia',
       'Trinidad & Tobago', 'Sierra Leone', 'Zambia', 'Chad',
       'Philippines', 'Haiti', 'Comoros', 'Libya', 'Panama',
       'São Tomé & Príncipe', 'Eritrea', 'Oman', 'Iraq', 'Burundi',
       'Fiji', 'New Caledonia', 'Lithuania', 'Luxembourg', 'Korea DPR',
       'Liechtenstein', 'St Kitts Nevis', 'Latvia', 'Suriname', 'Uganda',
       'El Salvador', 'Bermuda', 'Kuwait', 'Antigua & Barbuda',
       'Thailand', 'Mauritius', 'Guatemala', 'Liberia', 'Kazakhstan',
       'Niger', 'Mauritania', 'Montserrat', 'Namibia', 'Azerbaijan',
       'Guam', 'Faroe Islands', 'India', 'Nicaragua', 'Barbados',
       'Lebanon', 'Palestine', 'Guyana', 'Sudan', 'St Lucia', 'Ethiopia',
       'Puerto Rico', 'Grenada', 'Jordan', 'Rwanda', 'Qatar',
       'Afghanistan', 'Hong Kong', 'Andorra', 'Malta', 'Belize',
       'South Sudan', 'Indonesia', 'Botswana'], dtype=object)

In [59]:
f['Position'].unique()

array(['RF', 'ST', 'LW', 'GK', 'RCM', 'LF', 'RS', 'RCB', 'LCM', 'CB',
       'LDM', 'CAM', 'CDM', 'LS', 'LCB', 'RM', 'LAM', 'LM', 'LB', 'RDM',
       'RW', 'CM', 'RB', 'RAM', 'CF', 'RWB', 'LWB'], dtype=object)

In [62]:
f.groupby('Position').get_group('LW')

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,1,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
29,198219,L. Insigne,27,Italy,88,88,Napoli,62000.0,165.0,1,3.0,4.0,LW,2010,2022-01-01,5.333333,130.0,105400.0
30,197781,Isco,26,Spain,88,91,Real Madrid,73500.0,315.0,1,3.0,4.0,LW,2013,2022-01-01,5.750000,174.0,156200.0
32,189242,Coutinho,26,Brazil,88,89,FC Barcelona,69500.0,340.0,1,3.0,5.0,LW,2018,2023-01-01,5.666667,150.0,147700.0
55,222492,L. Sané,22,Germany,86,92,Manchester City,61000.0,195.0,0,2.0,4.0,LW,2016,2021-01-01,6.000000,165.0,125100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17727,242941,M. Bustgaard Larsen,18,Norway,53,70,Odds BK,120.0,1.0,0,1.0,2.0,LW,2017,2020-01-01,5.750000,143.0,225.0
17740,240650,R. Najjarine,18,Australia,52,71,Melbourne City FC,100.0,1.0,0,1.0,2.0,LW,2017,2020-01-01,5.750000,157.0,188.0
17899,244494,F. Delaveris,17,Norway,51,66,Odds BK,70.0,1.0,1,1.0,2.0,LW,2018,2020-01-01,5.750000,154.0,131.0
17938,245861,L. Cavallini,18,Italy,51,69,Foggia,80.0,1.0,0,1.0,2.0,LW,2018,2021-01-01,5.833333,157.0,178.0
18038,243790,Zhen'ao Wang,18,China PR,50,62,Vejle Boldklub,50.0,1.0,1,1.0,2.0,LW,2018,2020-01-01,5.750000,143.0,73.0

In [65]:
f.groupby(['Position','Nationality']).get_group(('LW',"Brazil"))

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,1,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.000000
32,189242,Coutinho,26,Brazil,88,89,FC Barcelona,69500.0,340.0,1,3.0,5.0,LW,2018,2023-01-01,5.666667,150.0,147700.000000
1143,238794,Vinícius Júnior,17,Brazil,77,92,Real Madrid,17500.0,66.0,1,1.0,5.0,LW,2018,2025-01-01,5.750000,161.0,46800.000000
1709,230468,José Mirazar,34,Brazil,75,75,Grêmio,3400.0,29.0,0,1.0,3.0,LW,2018,2021-01-01,5.916667,163.0,6100.000000
2656,204823,Nildo Petrolina,32,Brazil,73,73,CD Aves,3100.0,12.0,0,1.0,3.0,LW,2017,2019-01-01,5.750000,134.0,6500.000000
2832,229218,Pedro Rocha,23,Brazil,73,79,Spartak Moscow,5500.0,1.0,1,1.0,3.0,LW,2017,2021-01-01,5.833333,163.0,12700.000000
2898,239482,Galeno,20,Brazil,73,84,Rio Ave FC,7000.0,9.0,1,1.0,4.0,LW,2016,2019-06-30,6.000000,159.0,4585.060806
3006,192165,Paulinho,32,Brazil,73,73,BK Häcken,3100.0,5.0,1,1.0,4.0,LW,2015,2019-01-01,5.750000,165.0,3900.000000
3926,199412,Sebá,26,Brazil,72,73,Chongqing Dangdai Lifan FC SWM Team,3700.0,9.0,0,1.0,3.0,LW,2018,2021-01-01,5.833333,161.0,8100.000000
4863,232219,Bismark,24,Brazil,70,72,Al Qadisiyah,2200.0,10.0,1,1.0,3.0,LW,2016,2023-01-01,5.583333,172.0,3800.000000
5400,235706,Murilo Freitas,22,Brazil,70,80,Rio Ave FC,2900.0,6.0,0,1.0,4.0,LW,2016,2021-01-01,5.750000,146.0,6600.000000
6285,240046,João Victor,24,Brazil,69,72,LASK Linz,1300.0,6.0,0,1.0,4.0,LW,2017,2021-01-01,5.833333,159.0,2000.000000
6307,230581,Niltinho,24,Brazil,69,72,GD Chaves,1300.0,5.0,0,1.0,4.0,LW,2018,2022-01-01,5.750000,150.0,2900.000000
9800,245480,Dyjan Azevedo,27,Brazil,66,66,Paris FC,675.0,3.0,1,1.0,3.0,LW,2014,2019-01-01,5.583333,143.0,1200.000000
10180,192315,Henrique,33,Brazil,65,65,Brisbane Roar,325.0,2.0,1,1.0,3.0,LW,2018,2019-01-01,5.416667,132.0,406.000000

In [67]:
f

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,0,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,1,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,1,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,1,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,1,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,1,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,1,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,1,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,1,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,1,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [68]:
f.groupby(['Nationality','Club']).get_group(('Argentina','FC Barcelona'))

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,0,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0

In [70]:
# f.groupby(['Nationality','Club']).get_group(('FC Barcelona','Argentina'))

In [74]:
import warnings
warnings.filterwarnings('ignore')

f.groupby(['Nationality','Club'])['Age'].agg([max,min,'mean'])

                                max  min  mean
Nationality Club
Afghanistan Notts County         21   21  21.0
            Philadelphia Union   23   23  23.0
            SV Meppen            26   26  26.0
            Walsall              20   20  20.0
Albania     AC Ajaccio           22   22  22.0
...                             ...  ...   ...
Zimbabwe    Le Havre AC          22   22  22.0
            Nottingham Forest    26   26  26.0
            Orlando Pirates      24   22  23.0
            RSC Anderlecht       28   28  28.0
            Sparta Praha         32   32  32.0

[5155 rows x 3 columns]

In [75]:


f.groupby('Nationality')['Age'].agg([max,min,'mean'])

             max  min       mean
Nationality
Afghanistan   26   20  22.500000
Albania       34   18  24.025000
Algeria       35   19  27.050000
Andorra       28   28  28.000000
Angola        34   19  25.866667
...          ...  ...        ...
Uzbekistan    30   29  29.500000
Venezuela     34   18  24.313433
Wales         37   17  24.736434
Zambia        29   18  22.222222
Zimbabwe      34   22  26.846154

[164 rows x 3 columns]