In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.2.3'

In [ ]:
path='https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/CO2%20Emissions_Canada.csv'
path

'https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/CO2%20Emissions_Canada.csv'

In [ ]:
c=pd.read_csv(path)

In [ ]:
c[:3]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136

In [ ]:
c.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='object')

In [ ]:
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              7385 non-null   object
 1   Model                             7385 non-null   object
 2   Vehicle Class                     7385 non-null   object
 3   Engine Size(L)                    7385 non-null   float64
 4   Cylinders                         7385 non-null   int64
 5   Transmission                      7385 non-null   object
 6   Fuel Type                         7385 non-null   object
 7   Fuel Consumption City (L/100 km)  7385 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   7385 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  7385 non-null   float64
 10  Fuel Consumption Comb (mpg)       7385 non-null   int64
 11  CO2 Emissions(g/km)               7385 non-null   int64
dtypes: float64(4), int64(3), object(5)
memory usage: 692.5+ KB

In [ ]:
c.describe()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
count,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000
mean,3.160068,5.615030,12.556534,9.041706,10.975071,27.481652,250.584699
std,1.354170,1.828307,3.500274,2.224456,2.892506,7.231879,58.512679
min,0.900000,3.000000,4.200000,4.000000,4.100000,11.000000,96.000000
25%,2.000000,4.000000,10.100000,7.500000,8.900000,22.000000,208.000000
50%,3.000000,6.000000,12.100000,8.700000,10.600000,27.000000,246.000000
75%,3.700000,6.000000,14.600000,10.200000,12.600000,32.000000,288.000000
max,8.400000,16.000000,30.600000,20.600000,26.100000,69.000000,522.000000

In [ ]:
c.describe(include=object)

        Make      Model Vehicle Class Transmission Fuel Type
count   7385       7385          7385         7385      7385
unique    42       2053            16           27         5
top     FORD  F-150 FFV   SUV - SMALL          AS6         X
freq     628         32          1217         1324      3637

In [ ]:
c.describe(include=float)

,Engine Size(L),Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km)
count,7385.000000,7385.000000,7385.000000,7385.000000
mean,3.160068,12.556534,9.041706,10.975071
std,1.354170,3.500274,2.224456,2.892506
min,0.900000,4.200000,4.000000,4.100000
25%,2.000000,10.100000,7.500000,8.900000
50%,3.000000,12.100000,8.700000,10.600000
75%,3.700000,14.600000,10.200000,12.600000
max,8.400000,30.600000,20.600000,26.100000

In [ ]:
c.describe(include='int')

         Cylinders  Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)
count  7385.000000                  7385.000000          7385.000000
mean      5.615030                    27.481652           250.584699
std       1.828307                     7.231879            58.512679
min       3.000000                    11.000000            96.000000
25%       4.000000                    22.000000           208.000000
50%       6.000000                    27.000000           246.000000
75%       6.000000                    32.000000           288.000000
max      16.000000                    69.000000           522.000000

In [ ]:
c.describe(include='object')

        Make      Model Vehicle Class Transmission Fuel Type
count   7385       7385          7385         7385      7385
unique    42       2053            16           27         5
top     FORD  F-150 FFV   SUV - SMALL          AS6         X
freq     628         32          1217         1324      3637

In [ ]:
c['Make']

0       ACURA
1       ACURA
2       ACURA
3       ACURA
4       ACURA
        ...
7380    VOLVO
7381    VOLVO
7382    VOLVO
7383    VOLVO
7384    VOLVO
Name: Make, Length: 7385, dtype: object

In [ ]:
c['Make'].unique()

array(['ACURA', 'ALFA ROMEO', 'ASTON MARTIN', 'AUDI', 'BENTLEY', 'BMW',
       'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'DODGE', 'FIAT',
       'FORD', 'GMC', 'HONDA', 'HYUNDAI', 'INFINITI', 'JAGUAR', 'JEEP',
       'KIA', 'LAMBORGHINI', 'LAND ROVER', 'LEXUS', 'LINCOLN', 'MASERATI',
       'MAZDA', 'MERCEDES-BENZ', 'MINI', 'MITSUBISHI', 'NISSAN',
       'PORSCHE', 'RAM', 'ROLLS-ROYCE', 'SCION', 'SMART', 'SRT', 'SUBARU',
       'TOYOTA', 'VOLKSWAGEN', 'VOLVO', 'GENESIS', 'BUGATTI'],
      dtype=object)

In [ ]:
c['Make'].nunique()

42

In [ ]:
set(c['Make'])

{'ACURA',
 'ALFA ROMEO',
 'ASTON MARTIN',
 'AUDI',
 'BENTLEY',
 'BMW',
 'BUGATTI',
 'BUICK',
 'CADILLAC',
 'CHEVROLET',
 'CHRYSLER',
 'DODGE',
 'FIAT',
 'FORD',
 'GENESIS',
 'GMC',
 'HONDA',
 'HYUNDAI',
 'INFINITI',
 'JAGUAR',
 'JEEP',
 'KIA',
 'LAMBORGHINI',
 'LAND ROVER',
 'LEXUS',
 'LINCOLN',
 'MASERATI',
 'MAZDA',
 'MERCEDES-BENZ',
 'MINI',
 'MITSUBISHI',
 'NISSAN',
 'PORSCHE',
 'RAM',
 'ROLLS-ROYCE',
 'SCION',
 'SMART',
 'SRT',
 'SUBARU',
 'TOYOTA',
 'VOLKSWAGEN',
 'VOLVO'}

In [ ]:
c['Vehicle Class'].nunique()

16

In [ ]:
c['Cylinders'].nunique()

8

In [ ]:
set(c['Cylinders'])

{3, 4, 5, 6, 8, 10, 12, 16}

In [ ]:
c['Make'].value_counts()

Make
FORD             628
CHEVROLET        588
BMW              527
MERCEDES-BENZ    419
PORSCHE          376
TOYOTA           330
GMC              328
AUDI             286
NISSAN           259
JEEP             251
DODGE            246
KIA              231
HONDA            214
HYUNDAI          210
MINI             204
VOLKSWAGEN       197
MAZDA            180
LEXUS            178
JAGUAR           160
CADILLAC         158
SUBARU           140
VOLVO            124
INFINITI         108
BUICK            103
RAM               97
LINCOLN           96
MITSUBISHI        95
CHRYSLER          88
LAND ROVER        85
FIAT              73
ACURA             72
MASERATI          61
ROLLS-ROYCE       50
ASTON MARTIN      47
BENTLEY           46
LAMBORGHINI       41
ALFA ROMEO        30
GENESIS           25
SCION             22
SMART              7
BUGATTI            3
SRT                2
Name: count, dtype: int64

In [ ]:
c['CO2 Emissions(g/km)'].value_counts()

CO2 Emissions(g/km)
242    85
221    82
214    77
230    77
294    76
       ..
148     1
99      1
485     1
395     1
385     1
Name: count, Length: 331, dtype: int64

In [ ]:
c['Model'].value_counts()

Model
F-150 FFV               32
F-150 FFV 4X4           32
MUSTANG                 27
FOCUS FFV               24
SONIC                   20
                        ..
Camry TRD                1
Cullinan Black Badge     1
1500 4X4 EcoDiesel       1
1500 EcoDiesel           1
Sentra SR                1
Name: count, Length: 2053, dtype: int64

In [ ]:
c[['Make','Cylinders']].value_counts()

Make         Cylinders
PORSCHE      6            301
FORD         6            259
CHEVROLET    4            250
BMW          6            246
FORD         4            241
                         ...
BUICK        3              2
LINCOLN      8              2
LAMBORGHINI  8              2
SRT          10             2
FORD         10             1
Name: count, Length: 113, dtype: int64

In [ ]:
c[['Make','Cylinders']].value_counts()[::-1]

Make         Cylinders
FORD         10             1
SRT          10             2
LAMBORGHINI  8              2
LINCOLN      8              2
BUICK        3              2
                         ...
FORD         4            241
BMW          6            246
CHEVROLET    4            250
FORD         6            259
PORSCHE      6            301
Name: count, Length: 113, dtype: int64

In [ ]:
c[['Make','Cylinders','Vehicle Class']].value_counts()

Make        Cylinders  Vehicle Class
PORSCHE     6          MINICOMPACT                184
JEEP        4          SUV - SMALL                155
FORD        6          PICKUP TRUCK - STANDARD    120
VOLKSWAGEN  4          COMPACT                     99
GMC         8          SUV - STANDARD              94
                                                 ...
BUICK       6          FULL-SIZE                    1
BENTLEY     8          TWO-SEATER                   1
TOYOTA      6          PICKUP TRUCK - STANDARD      1
                       TWO-SEATER                   1
VOLVO       6          SUV - STANDARD               1
Name: count, Length: 422, dtype: int64

In [ ]:
c[['Make','Cylinders','Model']].value_counts()

Make           Cylinders  Model
FORD           4          FOCUS FFV        24
CHEVROLET      4          SONIC 5          20
                          SONIC            20
VOLKSWAGEN     4          JETTA            19
JEEP           4          COMPASS          19
                                           ..
MERCEDES-BENZ  8          CL 63 AMG         1
                          CL 550 4MATIC     1
VOLVO          6          XC70 3.2 AWD      1
                          XC60 T6 AWD       1
                          XC60 3.2 AWD      1
Name: count, Length: 2278, dtype: int64

In [ ]:
Name='Komal'

print('My name is:',Name)
print(f'My name is: { Name}')

My name is: Komal
My name is: Komal

In [ ]:
c.isna().sum()

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

In [ ]:
c.select_dtypes(include='int')

      Cylinders  Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)
0             4                           33                  196
1             4                           29                  221
2             4                           48                  136
3             6                           25                  255
4             6                           27                  244
...         ...                          ...                  ...
7380          4                           30                  219
7381          4                           29                  232
7382          4                           27                  240
7383          4                           29                  232
7384          4                           26                  248

[7385 rows x 3 columns]

In [ ]:
c.select_dtypes(include='float')

,Engine Size(L),Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km)
0,2.0,9.9,6.7,8.5
1,2.4,11.2,7.7,9.6
2,1.5,6.0,5.8,5.9
3,3.5,12.7,9.1,11.1
4,3.5,12.1,8.7,10.6
...,...,...,...,...
7380,2.0,10.7,7.7,9.4
7381,2.0,11.2,8.3,9.9
7382,2.0,11.7,8.6,10.3
7383,2.0,11.2,8.3,9.9
7384,2.0,12.2,8.7,10.7

In [ ]:
c.select_dtypes(include='object')

       Make        Model   Vehicle Class Transmission Fuel Type
0     ACURA          ILX         COMPACT          AS5         Z
1     ACURA          ILX         COMPACT           M6         Z
2     ACURA   ILX HYBRID         COMPACT          AV7         Z
3     ACURA      MDX 4WD     SUV - SMALL          AS6         Z
4     ACURA      RDX AWD     SUV - SMALL          AS6         Z
...     ...          ...             ...          ...       ...
7380  VOLVO  XC40 T5 AWD     SUV - SMALL          AS8         Z
7381  VOLVO  XC60 T5 AWD     SUV - SMALL          AS8         Z
7382  VOLVO  XC60 T6 AWD     SUV - SMALL          AS8         Z
7383  VOLVO  XC90 T5 AWD  SUV - STANDARD          AS8         Z
7384  VOLVO  XC90 T6 AWD  SUV - STANDARD          AS8         Z

[7385 rows x 5 columns]

In [ ]:
c.select_dtypes(include=['int','float'])

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,2.0,4,9.9,6.7,8.5,33,196
1,2.4,4,11.2,7.7,9.6,29,221
2,1.5,4,6.0,5.8,5.9,48,136
3,3.5,6,12.7,9.1,11.1,25,255
4,3.5,6,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...
7380,2.0,4,10.7,7.7,9.4,30,219
7381,2.0,4,11.2,8.3,9.9,29,232
7382,2.0,4,11.7,8.6,10.3,27,240
7383,2.0,4,11.2,8.3,9.9,29,232
7384,2.0,4,12.2,8.7,10.7,26,248

In [ ]:
c.select_dtypes(include='number')

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,2.0,4,9.9,6.7,8.5,33,196
1,2.4,4,11.2,7.7,9.6,29,221
2,1.5,4,6.0,5.8,5.9,48,136
3,3.5,6,12.7,9.1,11.1,25,255
4,3.5,6,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...
7380,2.0,4,10.7,7.7,9.4,30,219
7381,2.0,4,11.2,8.3,9.9,29,232
7382,2.0,4,11.7,8.6,10.3,27,240
7383,2.0,4,11.2,8.3,9.9,29,232
7384,2.0,4,12.2,8.7,10.7,26,248

In [ ]:
c.select_dtypes(exclude='object')

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,2.0,4,9.9,6.7,8.5,33,196
1,2.4,4,11.2,7.7,9.6,29,221
2,1.5,4,6.0,5.8,5.9,48,136
3,3.5,6,12.7,9.1,11.1,25,255
4,3.5,6,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...
7380,2.0,4,10.7,7.7,9.4,30,219
7381,2.0,4,11.2,8.3,9.9,29,232
7382,2.0,4,11.7,8.6,10.3,27,240
7383,2.0,4,11.2,8.3,9.9,29,232
7384,2.0,4,12.2,8.7,10.7,26,248

In [53]:
d=pd.DataFrame({'val':[[1,2,3],(10,20,30)]})
d

            val
0     [1, 2, 3]
1  (10, 20, 30)

In [ ]:
d['val'].map(sum)

0     6
1    60
Name: val, dtype: int64

In [45]:
d['val'].apply(lambda t:sum(t))

0     6
1    60
Name: val, dtype: int64

In [46]:
d

            val
0     [1, 2, 3]
1  (10, 20, 30)

In [54]:
d

            val
0     [1, 2, 3]
1  (10, 20, 30)

In [55]:
d['val'].apply(sum)

0     6
1    60
Name: val, dtype: int64

In [56]:
d

            val
0     [1, 2, 3]
1  (10, 20, 30)

In [57]:
d

            val
0     [1, 2, 3]
1  (10, 20, 30)

In [62]:
# d['val'][2]='Komal'
d.loc[2,'val']='Komal'

In [63]:
d

            val
0     [1, 2, 3]
1  (10, 20, 30)
2         Komal

In [64]:
def change(val):
    if isinstance(val,list):
        return 'hi'
    elif isinstance(val,tuple):
        return 'haa'
    else:
        return 'huuuu'


d['val'].apply(change)

0       hi
1      haa
2    huuuu
Name: val, dtype: object