PANDAS

In [1]:
import pandas as pd

In [2]:
''' pandas having main 3 data strucute

1.Series.....1D...rows
2.DataFrame....2D....contains rows and columns
3.Panel....DataFrame inside DataFrame
'''

s=pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
s=pd.series([1,2,3])   #s is always capital S
s

AttributeError: module 'pandas' has no attribute 'series'

In [7]:
s.ndim

1

In [8]:
s.shape

(4,)

In [9]:
s.size

4

In [10]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [12]:
s=pd.Series([1,2,3.])
s

0    1.0
1    2.0
2    3.0
dtype: float64

In [13]:
s=pd.Series([1,2,3.,4+5j])
s

0    1.0+0.0j
1    2.0+0.0j
2    3.0+0.0j
3    4.0+5.0j
dtype: complex128

In [14]:
s=pd.Series([1,2,3.,4+5j,'A'])
s

0         1
1         2
2       3.0
3    (4+5j)
4         A
dtype: object

In [16]:
s=pd.Series(range(11))
s

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [17]:
pd.Series(range(20,26))

0    20
1    21
2    22
3    23
4    24
5    25
dtype: int64

In [18]:
pd.Series

pandas.core.series.Series

In [19]:
pd.Series([1,2,3,4,5,6])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [21]:
pd.Series(data=[1,2,3,4,5,6],index=[101,102,103,104,105,106],dtype=int)

101    1
102    2
103    3
104    4
105    5
106    6
dtype: int64

In [22]:
pd.Series(data=[1,2,3,4,5,6],index=[101,102,103,104,105,106],dtype=float)

101    1.0
102    2.0
103    3.0
104    4.0
105    5.0
106    6.0
dtype: float64

In [26]:
pd.Series(data=[1,2,3,4,5,6],index=[101,102,103,104,105,106],dtype=complex)

101    1.0+0.0j
102    2.0+0.0j
103    3.0+0.0j
104    4.0+0.0j
105    5.0+0.0j
106    6.0+0.0j
dtype: complex128

In [25]:
pd.Series(data=[1,2,3,4,5,6],index=[101,102,103,104,105,106],dtype=bool)

101    True
102    True
103    True
104    True
105    True
106    True
dtype: bool

In [28]:
# downcasting is not allowed

s=pd.Series(data=[1,2.2,3.5])
s

0    1.0
1    2.2
2    3.5
dtype: float64

In [29]:
# downcasting is not allowed

s=pd.Series(data=[1,2.2,3.5],dtype=float)
s

0    1.0
1    2.2
2    3.5
dtype: float64

In [30]:
# downcasting is not allowed

s=pd.Series(data=[1,2.2,3.5],dtype=int)
s

ValueError: Trying to coerce float values to integers

In [31]:
pd.__version__

'2.2.3'

In [32]:
series_data=[10,20,30,40,50]
series_data_index=['id_'+ str(id) for id in range(len(series_data)) ]
pd.Series(data=series_data,index=series_data_index,dtype=float)

id_0    10.0
id_1    20.0
id_2    30.0
id_3    40.0
id_4    50.0
dtype: float64

In [33]:
s

0    1.0
1    2.2
2    3.5
dtype: float64

In [34]:
type(s)

pandas.core.series.Series

In [35]:
# DataFrame....2D

In [36]:
data=[['Suraj',21,20000],['Madhuri',25,30000]]
data

[['Suraj', 21, 20000], ['Madhuri', 25, 30000]]

In [38]:
# want to create dataframe from data

df=pd.DataFrame (data)
df

         0   1      2
0    Suraj  21  20000
1  Madhuri  25  30000

In [39]:
df=pd.DataFrame (data,columns=['Name','Age','Salary'])
df

      Name  Age  Salary
0    Suraj   21   20000
1  Madhuri   25   30000

In [44]:
# create a datafrmae using dict


sample={'Name':['Mahesh','Vishal','Sagar','Rahul','kamlesh'],
        'Salary':[25000,30000,15000,20000,50000],
        'Age':[30,25,20,35,23],
        'Place':['Pune','Nashik',"Mumbai",'Thane','Satara']
        }

sample

{'Name': ['Mahesh', 'Vishal', 'Sagar', 'Rahul', 'kamlesh'],
 'Salary': [25000, 30000, 15000, 20000, 50000],
 'Age': [30, 25, 20, 35, 23],
 'Place': ['Pune', 'Nashik', 'Mumbai', 'Thane', 'Satara']}

In [45]:
df=pd.DataFrame(sample)
df

      Name  Salary  Age   Place
0   Mahesh   25000   30    Pune
1   Vishal   30000   25  Nashik
2    Sagar   15000   20  Mumbai
3    Rahul   20000   35   Thane
4  kamlesh   50000   23  Satara

In [46]:
df=pd.DataFrame(sample)
print(df)

      Name  Salary  Age   Place
0   Mahesh   25000   30    Pune
1   Vishal   30000   25  Nashik
2    Sagar   15000   20  Mumbai
3    Rahul   20000   35   Thane
4  kamlesh   50000   23  Satara

In [47]:
df.query('Salary==30000')

     Name  Salary  Age   Place
1  Vishal   30000   25  Nashik

In [48]:
df.query('Salary<30000')

     Name  Salary  Age   Place
0  Mahesh   25000   30    Pune
2   Sagar   15000   20  Mumbai
3   Rahul   20000   35   Thane

In [49]:
df

      Name  Salary  Age   Place
0   Mahesh   25000   30    Pune
1   Vishal   30000   25  Nashik
2    Sagar   15000   20  Mumbai
3    Rahul   20000   35   Thane
4  kamlesh   50000   23  Satara

In [51]:
df.query("Name.str.endswith('h')")

      Name  Salary  Age   Place
0   Mahesh   25000   30    Pune
4  kamlesh   50000   23  Satara

In [58]:
df.query("Name.str.endswith('h') and Age<25")

      Name  Salary  Age   Place
4  kamlesh   50000   23  Satara

In [54]:
df.query("Place.str.startswith('P')")

     Name  Salary  Age Place
0  Mahesh   25000   30  Pune

In [52]:
'Mahesh'.endswith('h')

True

In [53]:
'Mahesh'.endswith('H')

False

In [61]:
df

      Name  Salary  Age   Place
0   Mahesh   25000   30    Pune
1   Vishal   30000   25  Nashik
2    Sagar   15000   20  Mumbai
3    Rahul   20000   35   Thane
4  kamlesh   50000   23  Satara

In [62]:
df.Name.str.endswith('h')

0     True
1    False
2    False
3    False
4     True
Name: Name, dtype: bool

In [63]:
df[df.Name.str.endswith('h')]

      Name  Salary  Age   Place
0   Mahesh   25000   30    Pune
4  kamlesh   50000   23  Satara

In [64]:
df

      Name  Salary  Age   Place
0   Mahesh   25000   30    Pune
1   Vishal   30000   25  Nashik
2    Sagar   15000   20  Mumbai
3    Rahul   20000   35   Thane
4  kamlesh   50000   23  Satara

In [80]:
data=[[1,2,3],['a','b','c'],[1.,2.,3.],[1,2,3,4]]

data

[[1, 2, 3], ['a', 'b', 'c'], [1.0, 2.0, 3.0], [1, 2, 3, 4]]

In [81]:
p=pd.DataFrame(data, columns=['A','B','C','D'])
p

     A    B    C    D
0    1    2    3  NaN
1    a    b    c  NaN
2  1.0  2.0  3.0  NaN
3    1    2    3  4.0

In [70]:
d =pd.DataFrame(data=[1,2,3,4],columns=['val'])
d

   val
0    1
1    2
2    3
3    4

In [71]:
import numpy as np

d =pd.DataFrame(data=[1,2,3,4,np.nan],columns=['val'])
d

   val
0  1.0
1  2.0
2  3.0
3  4.0
4  NaN

In [82]:
p

     A    B    C    D
0    1    2    3  NaN
1    a    b    c  NaN
2  1.0  2.0  3.0  NaN
3    1    2    3  4.0

In [87]:
p.to_csv('test.csv',index=False)

In [86]:
p.to_csv('test_1.csv',index=True)