In [ ]:
# PANDAS Continueeee...

In [ ]:

# https://github.com/hakimyameen/Datasets/blob/main/fifa_eda.csv

In [1]:
import pandas as pd

In [2]:
f = pd.read_csv('fifa_eda.csv')
f

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [7]:
path='https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv'
path

'https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv'

In [6]:
c=pd.read_csv(path)
c

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [5]:
f

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [8]:
f.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0

In [10]:
f.head(3)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0

In [12]:
f.head(50)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.000000
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.000000
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.000000
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.000000
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.000000
5,183277,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,Right,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.000000
6,177003,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.000000
7,176580,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.000000
8,155862,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.000000
9,200389,J. Oblak,25,Slovenia,90,93,Atlético Madrid,68000.0,94.0,Right,3.0,1.0,GK,2014,2021-01-01,6.166667,192.0,144500.000000
10,188545,R. Lewandowski,29,Poland,90,90,FC Bayern München,77000.0,205.0,Right,4.0,4.0,ST,2014,2021-01-01,6.000000,176.0,127100.000000
11,182521,T. Kroos,28,Germany,90,90,Real Madrid,76500.0,355.0,Right,4.0,3.0,LCM,2014,2022-01-01,6.000000,168.0,156800.000000
12,182493,D. Godín,32,Uruguay,90,90,Atlético Madrid,44000.0,125.0,Right,3.0,2.0,CB,2010,2019-01-01,6.166667,172.0,90200.000000
13,168542,David Silva,32,Spain,90,90,Manchester City,60000.0,285.0,Left,4.0,4.0,LCM,2010,2020-01-01,5.666667,148.0,111000.000000
14,215914,N. Kanté,27,France,89,90,Chelsea,63000.0,225.0,Right,3.0,2.0,LDM,2016,2023-01-01,5.500000,159.0,121300.000000
15,211110,P. Dybala,24,Argentina,89,94,Juventus,89000.0,205.0,Left,3.0,4.0,LF,2015,2022-01-01,5.833333,165.0,153500.000000
16,202126,H. Kane,24,England,89,91,Tottenham Hotspur,83500.0,205.0,Right,3.0,3.0,ST,2010,2024-01-01,6.166667,196.0,160700.000000
17,194765,A. Griezmann,27,France,89,90,Atlético Madrid,78000.0,145.0,Left,4.0,4.0,CAM,2014,2023-01-01,5.750000,161.0,165800.000000
18,192448,M. ter Stegen,26,Germany,89,92,FC Barcelona,58000.0,240.0,Right,3.0,1.0,GK,2014,2022-01-01,6.166667,187.0,123300.000000
19,192119,T. Courtois,26,Belgium,89,90,Real Madrid,53500.0,240.0,Left,4.0,1.0,GK,2018,2024-01-01,6.500000,212.0,113700.000000
20,189511,Sergio Busquets,29,Spain,89,89,FC Barcelona,51500.0,315.0,Right,4.0,3.0,CDM,2008,2023-01-01,6.166667,168.0,105600.000000
21,179813,E. Cavani,31,Uruguay,89,89,Paris Saint-Germain,60000.0,200.0,Right,4.0,3.0,LS,2013,2020-01-01,6.083333,170.0,111000.000000
22,167495,M. Neuer,32,Germany,89,89,FC Bayern München,38000.0,130.0,Right,5.0,1.0,GK,2011,2021-01-01,6.333333,203.0,62700.000000
23,153079,S. Agüero,30,Argentina,89,89,Manchester City,64500.0,300.0,Right,4.0,4.0,ST,2011,2021-01-01,5.666667,154.0,119300.000000
24,138956,G. Chiellini,33,Italy,89,89,Juventus,27000.0,215.0,Left,4.0,2.0,LCB,2005,2020-01-01,6.166667,187.0,44600.000000
25,231747,K. Mbappé,19,France,88,95,Paris Saint-Germain,81000.0,100.0,Right,3.0,5.0,RM,2018,2022-01-01,5.833333,161.0,166100.000000
26,209331,M. Salah,26,Egypt,88,89,Liverpool,69500.0,255.0,Left,3.0,4.0,RM,2017,2023-01-01,5.750000,157.0,137300.000000
27,200145,Casemiro,26,Brazil,88,90,Real Madrid,59500.0,285.0,Right,3.0,2.0,CDM,2013,2021-01-01,6.083333,185.0,126400.000000
28,198710,J. Rodríguez,26,Colombia,88,89,FC Bayern München,69500.0,315.0,Left,4.0,4.0,LAM,2016,2019-06-30,5.916667,172.0,4585.060806
29,198219,L. Insigne,27,Italy,88,88,Napoli,62000.0,165.0,Right,3.0,4.0,LW,2010,2022-01-01,5.333333,130.0,105400.000000
30,197781,Isco,26,Spain,88,91,Real Madrid,73500.0,315.0,Right,3.0,4.0,LW,2013,2022-01-01,5.750000,174.0,156200.000000
31,190460,C. Eriksen,26,Denmark,88,91,Tottenham Hotspur,73500.0,205.0,Right,3.0,4.0,CAM,2013,2020-01-01,5.916667,168.0,141500.000000
32,189242,Coutinho,26,Brazil,88,89,FC Barcelona,69500.0,340.0,Right,3.0,5.0,LW,2018,2023-01-01,5.666667,150.0,147700.000000
33,188567,P. Aubameyang,29,Gabon,88,88,Arsenal,59000.0,265.0,Right,3.0,4.0,LM,2018,2021-01-01,6.166667,176.0,112100.000000
34,178603,M. Hummels,29,Germany,88,88,FC Bayern München,46000.0,160.0,Right,4.0,3.0,LCB,2016,2021-01-01,6.250000,203.0,75900.000000
35,176676,Marcelo,30,Brazil,88,88,Real Madrid,43000.0,285.0,Left,4.0,5.0,LB,2007,2022-01-01,5.750000,176.0,88200.000000
36,173731,G. Bale,28,Wales,88,88,Real Madrid,60000.0,355.0,Left,4.0,4.0,ST,2013,2022-01-01,6.083333,181.0,123000.000000
37,167948,H. Lloris,31,France,88,88,Tottenham Hotspur,36000.0,150.0,Left,4.0,1.0,GK,2012,2022-01-01,6.166667,181.0,66600.000000
38,167664,G. Higuaín,30,Argentina,88,88,Milan,57000.0,245.0,Right,4.0,3.0,LS,2016,2019-06-30,6.083333,196.0,4585.060806
39,164240,Thiago Silva,33,Brazil,88,88,Paris Saint-Germain,24000.0,165.0,Right,4.0,2.0,RCB,2012,2020-01-01,6.000000,181.0,44400.000000
40,162835,S. Handanovič,33,Slovenia,88,88,Inter,30000.0,110.0,Right,3.0,1.0,GK,2012,2021-01-01,6.333333,203.0,51000.000000
41,1179,G. Buffon,40,Italy,88,88,Paris Saint-Germain,4000.0,77.0,Right,4.0,1.0,GK,2018,2019-01-01,6.333333,203.0,7400.000000
42,205600,S. Umtiti,24,France,87,92,FC Barcelona,57000.0,205.0,Left,3.0,2.0,CB,2016,2023-01-01,6.000000,165.0,121100.000000
43,201399,M. Icardi,25,Argentina,87,90,Inter,64500.0,130.0,Right,3.0,3.0,ST,2013,2021-01-01,5.916667,165.0,114500.000000
44,201024,K. Koulibaly,27,Senegal,87,90,Napoli,51000.0,115.0,Right,3.0,2.0,LCB,2014,2021-01-01,6.166667,196.0,90500.000000
45,195864,P. Pogba,25,France,87,91,Manchester United,64000.0,210.0,Right,4.0,5.0,RDM,2016,2021-01-01,6.333333,185.0,123200.000000
46,193041,K. Navas,31,Costa Rica,87,87,Real Madrid,30500.0,195.0,Right,3.0,1.0,GK,2014,2020-01-01,6.083333,176.0,62500.000000
47,192505,R. Lukaku,25,Belgium,87,89,Manchester United,62500.0,230.0,Left,3.0,3.0,ST,2017,2022-01-01,6.250000,207.0,120300.000000
48,192387,C. Immobile,28,Italy,87,87,Lazio,52000.0,115.0,Right,3.0,3.0,ST,2016,2023-01-01,6.083333,187.0,88400.000000
49,189332,Jordi Alba,29,Spain,87,87,FC Barcelona,38000.0,250.0,Left,3.0,3.0,LB,2012,2020-01-01,5.583333,150.0,77900.000000

In [13]:
f[0:3]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0

In [18]:
f[100:104]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
100,179844,Diego Costa,29,Spain,85,85,Atlético Madrid,38500.0,100.0,Right,4.0,2.0,LS,2018,2021-01-01,6.166667,190.0,78900.0
101,178518,R. Nainggolan,30,Belgium,85,85,Inter,35500.0,105.0,Right,3.0,3.0,CAM,2018,2022-01-01,5.750000,170.0,60400.0
102,171919,Naldo,35,Brazil,85,85,FC Schalke 04,9000.0,38.0,Right,3.0,2.0,CB,2016,2020-01-01,6.500000,201.0,15300.0
103,170890,B. Matuidi,31,France,85,85,Juventus,26000.0,145.0,Left,3.0,2.0,LM,2017,2020-01-01,5.916667,165.0,42900.0

In [19]:
f[30000:40000]

Empty DataFrame
Columns: [ID, Name, Age, Nationality, Overall, Potential, Club, Value, Wage, Preferred Foot, International Reputation, Skill Moves, Position, Joined, Contract Valid Until, Height, Weight, Release Clause]
Index: []

In [17]:
f[-3:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [16]:
f[-3:-1]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0

In [20]:
f.tail()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [21]:
f.tail(3)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [22]:
f[-5:]   #for last 5 records

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [24]:
f.sample(5)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
12989,231402,M. Penney,20,England,63,79,Sheffield Wednesday,725.0,4.0,Left,1.0,2.0,LB,2015,2020-01-01,5.750000,141.0,1800.000000
1323,193869,Gil,31,Brazil,76,76,Shandong Luneng TaiShan FC,5000.0,18.0,Right,2.0,2.0,LCB,2016,2021-01-01,6.333333,192.0,10800.000000
4469,202148,A. Khalili,26,Sweden,71,74,Kasimpaşa SK,2900.0,10.0,Right,1.0,3.0,CAM,2018,2021-01-01,6.000000,170.0,6100.000000
2187,215103,E. Puch,31,Chile,74,74,Querétaro,4900.0,26.0,Right,2.0,4.0,LM,2016,2018-12-31,5.500000,161.0,4585.060806
8606,213724,Bicho,22,Spain,67,75,Deportivo de La Coruña,1100.0,3.0,Left,1.0,3.0,CAM,2012,2019-01-01,5.666667,139.0,2000.000000

In [26]:
f.sample()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
11412,217190,A. Flores,27,El Salvador,64,64,Portland Timbers,475.0,2.0,Left,1.0,3.0,CM,2018,2019-01-01,5.583333,148.0,713.0

In [27]:
f.loc[:,:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [28]:
f.loc[:2,]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0

In [29]:
f.loc[0:2,]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0

In [31]:
f.loc[:2,'Name':'Nationality']

                Name  Age Nationality
0           L. Messi   31   Argentina
1  Cristiano Ronaldo   33    Portugal
2          Neymar Jr   26      Brazil

In [32]:
f.loc[0:10:3,'Name':'Overall']

        Name  Age Nationality  Overall
0   L. Messi   31   Argentina       94
3     De Gea   27       Spain       91
6  L. Modrić   32     Croatia       91
9   J. Oblak   25    Slovenia       90

In [33]:
f.loc[0:10:3,'Name':'Overall':2]

        Name Nationality
0   L. Messi   Argentina
3     De Gea       Spain
6  L. Modrić     Croatia
9   J. Oblak    Slovenia

In [35]:
f.loc[0:10:2,'Name':'Club':2]

              Name Nationality  Potential
0         L. Messi   Argentina         94
2        Neymar Jr      Brazil         93
4     K. De Bruyne     Belgium         92
6        L. Modrić     Croatia         91
8     Sergio Ramos       Spain         91
10  R. Lewandowski      Poland         90

In [36]:
s='python'

In [37]:
s[0]

'p'

In [38]:
s[-1]

'n'

In [39]:
s[:3]

'pyt'

In [40]:
s[-3:-1]

'ho'

In [41]:
s[-3:]

'hon'

In [42]:
f

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [47]:
f.loc[50:55]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
50,175943,D. Mertens,31,Belgium,87,87,Napoli,45000.0,135.0,Right,3.0,4.0,RF,2013,2020-01-01,5.583333,134.0,76500.0
51,172871,J. Vertonghen,31,Belgium,87,87,Tottenham Hotspur,34000.0,155.0,Left,3.0,3.0,LCB,2012,2019-01-01,6.166667,190.0,62900.0
52,171877,M. Hamšík,30,Slovakia,87,87,Napoli,46500.0,125.0,Right,3.0,3.0,LCM,2007,2020-01-01,6.000000,174.0,79100.0
53,168651,I. Rakitić,30,Croatia,87,87,FC Barcelona,46500.0,260.0,Right,4.0,3.0,RCM,2014,2021-01-01,6.000000,172.0,95300.0
54,152729,Piqué,31,Spain,87,87,FC Barcelona,34000.0,240.0,Right,4.0,2.0,RCB,2008,2022-01-01,6.333333,187.0,69700.0
55,222492,L. Sané,22,Germany,86,92,Manchester City,61000.0,195.0,Left,2.0,4.0,LW,2016,2021-01-01,6.000000,165.0,125100.0

In [48]:
f.loc[50:55:2]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
50,175943,D. Mertens,31,Belgium,87,87,Napoli,45000.0,135.0,Right,3.0,4.0,RF,2013,2020-01-01,5.583333,134.0,76500.0
52,171877,M. Hamšík,30,Slovakia,87,87,Napoli,46500.0,125.0,Right,3.0,3.0,LCM,2007,2020-01-01,6.000000,174.0,79100.0
54,152729,Piqué,31,Spain,87,87,FC Barcelona,34000.0,240.0,Right,4.0,2.0,RCB,2008,2022-01-01,6.333333,187.0,69700.0

In [49]:
f.loc[50:55:2,'ID':'Overall']

        ID        Name  Age Nationality  Overall
50  175943  D. Mertens   31     Belgium       87
52  171877   M. Hamšík   30    Slovakia       87
54  152729       Piqué   31       Spain       87

In [50]:
f.loc[50:55:2,'ID':'Overall':2]

        ID  Age  Overall
50  175943   31       87
52  171877   30       87
54  152729   31       87

In [51]:
f.loc[50:55:2,'ID':'Overall':3]

        ID Nationality
50  175943     Belgium
52  171877    Slovakia
54  152729       Spain

In [52]:
f

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [53]:
f.loc[50:60:2,::-1]   #for reverse the column

,Release Clause,Weight,Height,Contract Valid Until,Joined,Position,Skill Moves,International Reputation,Preferred Foot,Wage,Value,Club,Potential,Overall,Nationality,Age,Name,ID
50,76500.0,134.0,5.583333,2020-01-01,2013,RF,4.0,3.0,Right,135.0,45000.0,Napoli,87,87,Belgium,31,D. Mertens,175943
52,79100.0,174.0,6.000000,2020-01-01,2007,LCM,3.0,3.0,Right,125.0,46500.0,Napoli,87,87,Slovakia,30,M. Hamšík,171877
54,69700.0,187.0,6.333333,2022-01-01,2008,RCB,2.0,4.0,Right,240.0,34000.0,FC Barcelona,87,87,Spain,31,Piqué,152729
56,114500.0,141.0,5.666667,2022-01-01,2017,RW,4.0,2.0,Left,180.0,59500.0,Manchester City,91,86,Portugal,23,Bernardo Silva,218667
58,102700.0,152.0,5.750000,2023-01-01,2016,LM,4.0,3.0,Right,195.0,52000.0,Liverpool,87,86,Senegal,26,S. Mané,208722
60,108800.0,152.0,5.583333,2023-01-01,2015,RW,4.0,3.0,Right,195.0,56500.0,Manchester City,89,86,England,23,R. Sterling,202652

In [54]:
f.loc[50:60:2,['Club','Age','Name']]

               Club  Age            Name
50           Napoli   31      D. Mertens
52           Napoli   30       M. Hamšík
54     FC Barcelona   31           Piqué
56  Manchester City   23  Bernardo Silva
58        Liverpool   26         S. Mané
60  Manchester City   23     R. Sterling

In [56]:
f.loc[50:60:2,('Club','Age','Name')]

               Club  Age            Name
50           Napoli   31      D. Mertens
52           Napoli   30       M. Hamšík
54     FC Barcelona   31           Piqué
56  Manchester City   23  Bernardo Silva
58        Liverpool   26         S. Mané
60  Manchester City   23     R. Sterling

In [55]:
f.loc[50:60:2,['Club','Age','NamE']]

KeyError: "['NamE'] not in index"

In [57]:
f.set_index('ID')   #donot use this

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
ID,,,,,,,,,,,,,,,,,
158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0